logging:
  level:
    root: info
server:
  port: 8083

spring:
  application:
    name:
      cim-server
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 100
          max-idle: 100
          max-wait: 1000
          min-idle: 10
springdoc:
  swagger-ui:
    enabled: true

im:
  route:
    url: http://localhost:8083
  heartbeat:
    time: 30
  port: 10086

meta:
  uri: 127.0.0.1:2181
  switch: true
  timeout: 30000